disabled_rules:
 - trailing_whitespace
 - function_body_length
 - nesting
excluded:
  - Pods
  - HubStarsTests
  - HubStarsUITests

identifier_name:
  min_length: 2
force_cast: warning
line_length: 140
type_name:
  validates_start_with_lowercase: false