# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HubStars' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HubStars
  pod 'SwiftLint'

  target 'HubStarsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    pod 'iOSSnapshotTestCase'
  end
  
end
